services:
  tournament:
    container_name: tournament
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
      args:
        - SECRET=${SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_PRICE_POOL=${NEXT_PUBLIC_PRICE_POOL}
    environment:
      - SECRET=${SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXT_PUBLIC_PRICE_POOL=${NEXT_PUBLIC_PRICE_POOL}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tournament.rule=Host(`tournament.barron.agency`)"
      - "traefik.http.routers.tournament.entrypoints=websecure"
      - "traefik.http.routers.tournament.tls.certresolver=letsencrypt"
      - "traefik.http.services.tournament.loadbalancer.server.port=3000"

networks:
  proxy:
    external: false
    name: proxy
